### ISSUE TITLE
Is there any example about how to train model with large embeddings?

### ISSUE THREAD

**Issue by RunfengZhang** [facebookresearch/torchrec#5]
Is there any example about how to train model with large embeddings? Here, I mean something like splitting the embedding table of two towel model into different GPUs?

**Comment by colin2328** [comment]
Hi @RunfengZhang 

The DLRM example is training model with large embeddings and which shards the tables. You can see in the README https://github.com/facebookresearch/torchrec/blob/main/torchrec/examples/dlrm/README.MD how to run and some of the embedding size configurations.

if you are looking for a two tower model, we have a toy example https://github.com/facebookresearch/torchrec/blob/main/torchrec/examples/notebooks/movielens_tutorial.ipynb . This example doesn't use DistributedModelParallel to split embedding tables yet, but we plan to improve it to do so.
